// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef panel_h
#define panel_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "panel_cb.h"
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *wKeyOn;
extern Fl_Light_Button *wEngineOn;
#include <FL/Fl_Choice.H>
extern Fl_Choice *wKeyState;
#include "Fl_CairoBox.h"
extern Fl_CairoBox *wCarBox;
Fl_Double_Window* makePanelWindow();
#endif
