// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "panel.h"

Fl_Light_Button *wKeyOn=(Fl_Light_Button *)0;

Fl_Light_Button *wEngineOn=(Fl_Light_Button *)0;

Fl_Choice *wKeyState=(Fl_Choice *)0;

Fl_CairoBox *wCarBox=(Fl_CairoBox *)0;

Fl_Double_Window* makePanelWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(500, 375);
    w = o;
    { wKeyOn = new Fl_Light_Button(5, 10, 100, 35, "Key On");
    } // Fl_Light_Button* wKeyOn
    { wEngineOn = new Fl_Light_Button(5, 45, 100, 35, "Engine On");
    } // Fl_Light_Button* wEngineOn
    { wKeyState = new Fl_Choice(380, 10, 110, 20, "Key State");
      wKeyState->down_box(FL_BORDER_BOX);
    } // Fl_Choice* wKeyState
    { wCarBox = new Fl_CairoBox(325, 64, 160, 182, "Car");
      wCarBox->box(FL_NO_BOX);
      wCarBox->color(FL_BACKGROUND_COLOR);
      wCarBox->selection_color(FL_BACKGROUND_COLOR);
      wCarBox->labeltype(FL_NORMAL_LABEL);
      wCarBox->labelfont(0);
      wCarBox->labelsize(14);
      wCarBox->labelcolor(FL_FOREGROUND_COLOR);
      wCarBox->align(Fl_Align(FL_ALIGN_CENTER));
      wCarBox->when(FL_WHEN_RELEASE);
    } // Fl_CairoBox* wCarBox
    o->end();
  } // Fl_Double_Window* o
  return w;
}
